plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.1.21'
}

task downloadAndUnzipNativeLibs {
    group = 'Pre-build'
    description = 'Downloads and unzips libsherpa-mnn-jni native library from CDN.'
    def nativeLibsUrl = 'https://meta.alicdn.com/data/mnn/libs/libsherpa-mnn-jni-16k.zip'
    def zipFileName = 'libsherpa-mnn-jni-16k.zip'
    def outputDir = file('src/main/jniLibs/arm64-v8a')
    def downloadedZip = new File(project.buildDir, zipFileName)
    def checkFile = new File(outputDir, 'libsherpa-mnn-jni.so')
    inputs.property('url', nativeLibsUrl)
    outputs.file(checkFile)
    doLast {
        println "-> Executing downloadAndUnzipNativeLibs task..."
        println "   Downloading from ${nativeLibsUrl}"
        println "   outputDir  ${outputDir}"
        println "   downloadedZip  ${downloadedZip}"
        outputDir.mkdirs()
        downloadedZip.parentFile.mkdirs()
        ant.get(src: nativeLibsUrl, dest: downloadedZip)
        if (!downloadedZip.exists()) {
            throw new GradleException("Download failed: ${downloadedZip} not found.")
        }
        println "   Download complete."
        println "   Unzipping ${downloadedZip.name} to ${outputDir}..."
        copy {
            from(zipTree(downloadedZip))
            into(outputDir)
        }
        println "   Unzip complete."
        downloadedZip.delete()
    }
    onlyIf {
        println "-> Checking if native libs exist... [Exists: ${checkFile.exists()}]"
        return !checkFile.exists()
    }
}

preBuild.dependsOn downloadAndUnzipNativeLibs

android {
    namespace 'com.alibaba.mnnllm.multimodal.audio'
    compileSdk 35
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "com.alibaba.mnnllm.multimodal.audio"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
    
    // MNN & Frameworks
    implementation project(':mnn_tts')
    implementation project(':model_downloader')
    
    // Timber for logging
    implementation "com.jakewharton.timber:timber:5.0.1"
}
